openapi: 3.0.1
info:
  title: TODO Plugin
  description: A plugin that allows the user to create and manage a TODO list using ChatGPT.
  version: 'v1'
servers:
  - url: https://greasy-jessika-digital-alpha.koyeb.app/
paths:
  /get_investor_details:
    post:
      operationId: get_investor_details
      summary: Get an array of Investor name in database and it's CIK from it's regular name
      description: Something
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetInvestorDetailsRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetInvestorDetailsResponse'
      responses:
        "300":
          description: CIK NOT FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetInvestorDetailsResponseIfNull'
  /get_issuer_details:
    post:
      operationId: get_issuer_details
      summary: Get the issuer name cusip and issuer code of a particular asset from it's name
      description: cusip is unique to security while issuer code is for a issuer to search for details of issuer use issuer code
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetIssuerDetailsRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetIssuerDetailsResponse'
      responses:
        "300":
          description: CUSIP NOT FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetIssuerDetailsResponseIfNull'
  /get_filings:
    post:
      operationId: get_filings
      summary: RUn query to get records on a Db having 13F documents
      description:  schema \n \ninvestor_cik,\nperiod_of_report timestamp,\ninvestor_name,\ntitle_of_class,\ncusip,\nissuer_code,\nvalue_in_dollars,\nshrs_or_prn_amt and table name aggregate_filings
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetFilingsRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilingsResponse'
      responses:
        "300":
          description: QUERY NOT FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilingsResponseIfNull'
components:
  schemas:
    GetInvestorDetailsRequest:
      title: GetInvestorCikRequest
      required:
        - investor_name
      type: object
      properties:
        investor_name:
          title: InvestorName
          type: string
          description: The Name of investor we want to know CIK.
    GetIssuerDetailsRequest:
      title: GetIssuerCusipRequest
      required:
        - issuer_name
      type: object
      properties:
        issuer_name:
          title: IssuerName
          type: string
          description: The Name of issuer/asset we want to know cusip.
    GetFilingsRequest:
      title: GetFilingsRequest
      required:
        - db_query
      type: object
      properties:
        db_query:
          title: Database Query
          type: string
          description: The Query that has to be ran on Db.
    GetInvestorDetailsResponse:
      title: GetInvestorCikResponse
      required:
        - results
      type: object
      properties:
        results:
          title: Results
          type: object
          description: Object containing investor information
          properties:
            investor_name:
              title: Investor Name
              type: array
              description: Array of investor names
              items:
                type: string
            cik:
              title: CIK
              type: array
              description: Array of CIK (Central Index Key) numbers
              items:
                type: string
    GetInvestorDetailsResponseIfNull:
      title: GetInvestorCikResponseIfNull
      required:
        - results
      type: object
      properties:
        results:
          title: Results
          type: string
          description: If the specified investor is not found
    GetIssuerDetailsResponse:
      title: GetIssuerCusipResponse
      required:
        - results
      type: object
      properties:
        results:
          title: Results
          type: object
          description: Object containing investor information
          properties:
            name_of_issuer:
              title: Issuer/Asset Name
              type: array
              description: Array of investor/assets names
              items:
                type: string
            cusip:
              title: CUSIP
              type: array
              description: Array of CUSIPs of assets
              items:
                type: string
            issuer_code:
              title: Issuer code
              type: array
              description: This is issuer code that is specific to one issuer
              items:
                type: string
    GetIssuerDetailsResponseIfNull:
      title: GetIssuerCusipResponseIfNull
      required:
        - results
      type: object
      properties:
        results:
          title: Results
          type: string
          description: If the specified asset/issuer is not found
    GetFilingsResponse:
      title: GetFilingsResponse
      required:
        - results
      type: object
      properties:
        results:
          title: Results
          type: string
          description: CSV of values from the database
    GetFilingsResponseIfNull:
      title: GetFilingsResponseIfNull
      required:
        - results
      type: object
      properties:
        results:
          title: Results
          type: string
          description: If the specified query is not found
